Repository MTVS-Muze/back-end, pull requests merged in 2023-10, with the labels that each got.

#4 [#1] Member domain 기능 구현
  src/main/java/com/muze/MuzeApplication.java
  src/main/java/com/muze/domain/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/muze/domain/member/command/application/dto/UpdateMemberDTO.java
  src/main/java/com/muze/domain/member/command/application/service/CreateMemberService.java
  src/main/java/com/muze/domain/member/command/application/service/UpdateMemberService.java
  src/main/java/com/muze/domain/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/muze/domain/member/command/domain/aggregate/entity/enumtype/Role.java
  src/main/java/com/muze/domain/member/command/domain/repository/MemberRepository.java
  src/main/java/com/muze/domain/member/query/application/dto/FindMemberDTO.java
  src/main/java/com/muze/domain/member/query/application/service/FindMemberService.java
  src/main/java/com/muze/domain/member/query/domain/repository/MemberMapper.java
  src/main/java/com/muze/domain/security/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/muze/global/configration/AppProperties.java
  src/main/java/com/muze/global/configration/DatabaseConfiguration.java
  src/main/java/com/muze/global/configration/TomcatWebConfiguration.java
  src/main/java/com/muze/global/configration/WebConfiguration.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: ✨ Feature

#6 [closes #1] Member Domain 기능 구현
  src/test/java/com/muze/domain/member/command/application/service/CreateMemberServiceTests.java
Labels: ✨ Feature, ✅ Test

#8 [Closes #7] Feat : Init Swagger
  src/main/java/com/muze/global/configration/SwaggerConfiguration.java
Labels: 📬 API, 📃 Docs, ✨ Feature

#20 [Closes #13]Feat : 좋아요 controller 및 관련기능 구현 Test : 좋아요 여부 및 개수 기능 테스트
  src/main/java/com/muze/domain/like/command/application/controller/LikeController.java
  src/main/java/com/muze/domain/like/command/application/service/CancelLikeService.java
  src/main/java/com/muze/domain/like/command/application/service/EnrollLikeService.java
  src/main/java/com/muze/domain/like/command/domain/repository/LikeRepository.java
  src/main/java/com/muze/domain/like/query/application/dto/LikeInfoDTO.java
  src/main/java/com/muze/domain/like/query/application/service/LikeInfoService.java
  src/main/java/com/muze/domain/like/query/domain/repository/LikeMapper.java
  src/main/resources/mapper/Like/LikeMapper.xml
  src/test/java/com/muze/like/repository/LikeRepositoryTests.java
  src/test/java/com/muze/like/service/LikeServiceTests.java
Labels: 📬 API, ✨ Feature, ✅ Test

#21 [Closes #19] title, song column 추가 및 코드수정
  src/main/java/com/muze/domain/map/command/application/dto/RequestMapDTO.java
  src/main/java/com/muze/domain/map/command/application/dto/ResponseMapDTO.java
  src/main/java/com/muze/domain/map/command/application/service/CreateMapService.java
  src/main/java/com/muze/domain/map/command/application/service/UpdateMapService.java
  src/main/java/com/muze/domain/map/command/domain/aggregate/entity/Map.java
  src/test/java/com/muze/domain/map/command/application/service/CUDMapServiceTests.java
Labels: 🏗️ Refactoring, ✅ Test

#26 [#24] Map domain Controller
  src/main/java/com/muze/domain/map/command/application/controller/MapController.java
  src/main/java/com/muze/global/configration/SecurityConfiguration.java
  src/main/java/com/muze/global/configration/SwaggerConfiguration.java
Labels: 📬 API, ✨ Feature

#31 [closes #30] Map Entity 생성날짜 컬럼 추가
  src/main/java/com/muze/domain/map/command/application/dto/ResponseMapDTO.java
  src/main/java/com/muze/domain/map/command/application/service/CreateMapService.java
  src/main/java/com/muze/domain/map/command/domain/aggregate/entity/Map.java
  src/main/java/com/muze/domain/map/query/application/dto/FindMapDTO.java
  src/main/resources/mapper/map/MapMapper.xml
Labels: 🏗️ Refactoring

#27 [Closes #22]Feat : Playlist entity 생성
  src/main/java/com/muze/domain/playlist/command/domain/aggregate/entity/Playlist.java
  src/main/java/com/muze/domain/playlist/command/domain/aggregate/vo/MemberVO.java
Labels: ✨ Feature

#36 [Closes #33]Feat : playlist, mapinplaylist의 controller 작성
  src/main/java/com/muze/domain/like/command/domain/aggregate/originenum/Origin.java
  src/main/java/com/muze/domain/like/query/application/service/LikeInfoService.java
  src/main/java/com/muze/domain/mapinplaylist/command/application/contoller/PlaylistInMapController.java
  src/main/java/com/muze/domain/mapinplaylist/query/application/controller/MapInPlaylistQueryController.java
  src/main/java/com/muze/domain/mapinplaylist/query/application/dto/MapInPlaylistInfoDTO.java
  src/main/java/com/muze/domain/mapinplaylist/query/application/service/MapInPlaylistInfoService.java
  src/main/java/com/muze/domain/mapinplaylist/query/domain/repository/MapInPlaylistMapper.java
  src/main/java/com/muze/domain/playlist/command/application/controller/PlaylistController.java
  src/main/java/com/muze/domain/playlist/query/application/controller/PlaylistQueryController.java
  src/main/java/com/muze/domain/playlist/query/application/dto/PlaylistDTO.java
  src/main/java/com/muze/domain/playlist/query/application/service/PlaylistInfoService.java
  src/main/java/com/muze/domain/playlist/query/domain/repository/PlaylistMapper.java
  src/main/resources/mapper/mapinplaylist/MapInPlaylistMapper.xml
  src/main/resources/mapper/playlist/PlaylistMapper.xml
  src/test/java/com/muze/domain/like/repository/LikeRepositoryTests.java
  src/test/java/com/muze/domain/like/service/LikeServiceTests.java
  src/test/java/com/muze/domain/mapinplaylist/repository/MapInPlaylistRepositoryTests.java
  src/test/java/com/muze/domain/mapinplaylist/service/MapInPlaylistServiceTests.java
  src/test/java/com/muze/domain/playlist/repository/PlaylistRepositoryTests.java
  src/test/java/com/muze/domain/playlist/service/PlaylistServiceTests.java
Labels: 📬 API, ✨ Feature, ✅ Test

#37 [closes #34] csv file 요청 처리
  build.gradle
  src/main/java/com/muze/domain/map/command/application/controller/MapController.java
  src/main/java/com/muze/domain/map/command/application/dto/RequestMapDTO.java
  src/main/java/com/muze/domain/map/command/application/service/CreateMapService.java
  src/main/java/com/muze/domain/map/command/application/service/UpdateMapService.java
  src/main/java/com/muze/domain/map/query/application/controller/FindMapController.java
  src/main/java/com/muze/domain/map/query/application/dto/FindMapDTO.java
  src/main/java/com/muze/domain/map/query/application/dto/FindResponseDTO.java
  src/main/java/com/muze/domain/map/query/application/service/FindMapService.java
  src/main/java/com/muze/domain/map/query/domain/repository/MapMapper.java
  src/main/java/com/muze/domain/map/query/domain/service/CsvFileService.java
  src/main/resources/mapper/map/MapMapper.xml
  src/test/java/com/muze/domain/map/command/application/service/CUDMapServiceTests.java
Labels: ✨ Feature

#39 [closes #38] dto 수정
  src/main/java/com/muze/domain/map/command/application/dto/RequestMapDTO.java
  src/main/java/com/muze/domain/map/query/application/dto/FindMapDTO.java
  src/test/java/com/muze/domain/map/command/application/service/CUDMapServiceTests.java
Labels: 🏗️ Refactoring
