Repository MTVS-Muze/back-end, pull requests merged in 2023-11, with the labels that each got.

#41 [closes #40] Token Filter 적용
  src/main/java/com/muze/global/configration/SecurityConfiguration.java
  src/main/java/com/muze/global/filter/AuthenticationExceptionFilter.java
  src/main/java/com/muze/global/filter/NullPointExceptionFilter.java
Labels: ✨ Feature

#46 Feature/friend 44 add delete friend
  src/main/java/com/muze/domain/friend/command/application/dto/FriendDTO.java
  src/main/java/com/muze/domain/friend/command/application/service/AddFriendService.java
  src/main/java/com/muze/domain/friend/command/application/service/DeleteFriendService.java
  src/main/java/com/muze/domain/friend/command/domain/aggregate/entity/Friend.java
  src/main/java/com/muze/domain/friend/command/domain/aggregate/vo/FriendVO.java
  src/main/java/com/muze/domain/friend/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/muze/domain/friend/command/domain/repository/FriendRepository.java
  src/main/java/com/muze/domain/friend/command/domain/service/FriendService.java
  src/test/java/com/muze/domain/friend/service/FriendServiceTests.java
Labels: ✨ Feature, ✅ Test

#43 [Closes #42]Feat : friend context entity 작성
  src/main/java/com/muze/domain/friend/command/domain/aggregate/entity/Friend.java
  src/main/java/com/muze/domain/friend/command/domain/aggregate/vo/FriendVO.java
  src/main/java/com/muze/domain/friend/command/domain/aggregate/vo/MemberVO.java
Labels: ✨ Feature

#47 [Closes #45]Feat : 친구 context controller 작성
  build.gradle
  src/main/java/com/muze/domain/friend/command/application/controller/FriendController.java
  src/main/java/com/muze/domain/friend/command/application/dto/FriendDTO.java
  src/main/java/com/muze/domain/friend/command/application/service/AddFriendService.java
  src/main/java/com/muze/domain/friend/command/domain/repository/FriendRepository.java
  src/main/java/com/muze/domain/friend/query/application/controller/FriendQueryController.java
  src/main/java/com/muze/domain/friend/query/application/dto/FriendListsDTO.java
  src/main/java/com/muze/domain/friend/query/application/service/FindFriendsService.java
  src/main/java/com/muze/domain/friend/query/domain/repository/FriendMapper.java
  src/main/java/com/muze/domain/friend/query/domain/service/CheckMemberService.java
  src/main/java/com/muze/domain/friend/query/infra/service/CheckMemberService.java
  src/main/java/com/muze/domain/like/command/application/controller/LikeController.java
  src/main/java/com/muze/domain/like/command/application/dto/LikeDTO.java
  src/main/java/com/muze/global/configration/SecurityConfiguration.java
  src/main/java/com/muze/global/configration/SwaggerConfiguration.java
  src/main/resources/mapper/firend/FriendMapper.xml
  src/test/java/com/muze/domain/friend/repository/FriendRepositoryTests.java
  src/test/java/com/muze/domain/friend/service/FriendServiceTests.java
Labels: 📬 API, ✨ Feature, ✅ Test

#50 [closes #49] Token으로 회원정보 조회
  src/main/java/com/muze/domain/member/query/application/controller/MemberController.java
  src/main/java/com/muze/global/common/annotation/CurrentMember.java
  src/main/java/com/muze/global/common/annotation/CustomApiResponse.java
  src/main/java/com/muze/global/configration/SecurityConfiguration.java
  src/main/java/com/muze/global/configration/SwaggerConfiguration.java
  src/main/java/com/muze/global/filter/TokenAuthenticationFilter.java
  src/main/java/com/muze/global/security/command/application/controller/AuthController.java
  src/main/java/com/muze/global/security/command/application/dto/AuthResponse.java
  src/main/java/com/muze/global/security/command/application/dto/AuthResponseBody.java
  src/test/java/com/muze/domain/map/command/application/service/CUDMapServiceTests.java
Labels: ✨ Feature

#51 [#48] column 추가 및 코드 리팩토링
  src/main/java/com/muze/domain/map/command/application/controller/MapController.java
  src/main/java/com/muze/domain/map/command/application/dto/RequestMapDTO.java
  src/main/java/com/muze/domain/map/command/application/dto/ResponseMapDTO.java
  src/main/java/com/muze/domain/map/command/application/service/CreateMapService.java
  src/main/java/com/muze/domain/map/command/application/service/UpdateMapService.java
  src/main/java/com/muze/domain/map/command/domain/aggregate/entity/Map.java
  src/main/java/com/muze/domain/map/query/application/controller/FindMapController.java
  src/main/java/com/muze/domain/map/query/application/dto/FindMapDTO.java
  src/main/java/com/muze/domain/map/query/application/service/FindMapService.java
  src/main/java/com/muze/domain/map/query/domain/service/MemberRequest.java
  src/main/java/com/muze/domain/map/query/infra/service/MemberRequestService.java
  src/main/java/com/muze/global/common/annotation/InfraService.java
  src/main/resources/mapper/map/MapMapper.xml
Labels: ✨ Feature, 🏗️ Refactoring

#53 [closes #52] Swagger 코드 추가 및 정리
  src/main/java/com/muze/domain/map/command/application/controller/MapController.java
  src/main/java/com/muze/domain/map/command/application/dto/CreateMapDTO.java
  src/main/java/com/muze/domain/map/command/application/dto/ResponseMapDTO.java
  src/main/java/com/muze/domain/map/command/application/service/CreateMapService.java
  src/main/java/com/muze/domain/map/command/application/service/DeleteMapService.java
  src/main/java/com/muze/domain/map/command/application/service/UpdateMapService.java
  src/main/java/com/muze/domain/map/query/application/controller/FindMapController.java
  src/main/java/com/muze/domain/map/query/application/dto/FindMapDTO.java
  src/main/java/com/muze/domain/map/query/application/dto/FindResponseDTO.java
  src/main/java/com/muze/domain/map/query/application/service/FindMapService.java
  src/main/java/com/muze/domain/map/query/domain/repository/MapMapper.java
  src/main/java/com/muze/domain/member/query/application/controller/MemberController.java
  src/main/java/com/muze/domain/member/query/application/dto/FindMemberDTO.java
  src/main/resources/mapper/map/MapMapper.xml
Labels: 📬 API, 🏗️ Refactoring

#59 [closes #58] 예외처리
  src/main/java/com/muze/domain/map/command/application/dto/CreateMapDTO.java
  src/main/java/com/muze/domain/map/command/domain/aggregate/entity/Map.java
  src/main/java/com/muze/global/common/response/MapErrorResponse.java
  src/main/java/com/muze/global/handler/MapExceptionHandler.java
Labels: ✨ Feature

#61 [Closes #60]Feat : tie column 추가
  src/main/java/com/muze/domain/character/command/application/dto/CharacterCustomizingDTO.java
  src/main/java/com/muze/domain/character/command/application/service/CharacterCustomizingService.java
  src/main/java/com/muze/domain/character/command/domain/aggregate/entity/Character.java
  src/main/java/com/muze/domain/character/command/domain/service/CharacterService.java
  src/main/java/com/muze/domain/character/query/application/dto/MyCharacterDTO.java
  src/main/resources/mapper/character/CharacterMapper.xml
  src/test/java/com/muze/domain/character/characterTests.java
Labels: 📬 API, ✨ Feature
